### ISSUE TITLE
我是 yapi 作者，加个好友交流下

### ISSUE THREAD

**Issue by hellosean1025** [bolin-L/nicon#11]
...

**Comment by rambler36** [comment]
``你好，我使用Yapi时我们自己封装了一个返回对象，已经改成泛型的类型，所以打出jar包后引用会泛型擦除，导致返回参数无法打印到Yapi的接口文档里，不知道是否可以有什么办法解决呢。


下面是jar的代码：
`//
// Source code recreated from a .class file by IntelliJ IDEA
// (powered by Fernflower decompiler)
//


import com.alibaba.fastjson.annotation.JSONType;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.joy.error.BusinessException;
import com.joy.error.BusinessNoTransactionalException;
import com.joy.error.FeignCallException;
import com.joy.error.JoyException;
import com.joy.error.JoyNoTransactionalException;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.Map;
import java.util.Properties;
import org.apache.commons.lang.StringUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@JSONType(
    ignores = {"dataUse"}
)
@JsonIgnoreProperties(
    ignoreUnknown = true,
    value = {"dataUse"}
)
public class ResponseBean<T> {
    private static final Logger logger = LoggerFactory.getLogger(ResponseBean.class);
    private T data;
    private String code;
    private String message;
    private Map<String, Object> err;

    public static <T> ResponseBean<T> success(T data) {
        //此处会发生泛型擦除，导致返回参数无法打印
        //ResponseBean<T> response = new ResponseBean<T>();//擦除前
        ResponseBean<T> response = new ResponseBean();//实际jar内
        response.setData(data);
        return response;
    }

    public static ResponseBean fail() {
        return new ResponseBean((String)null);
    }

    public static ResponseBean fail(String message) {
        return new ResponseBean(message);
    }

    public static ResponseBean fail(String message, String code) {
        return new ResponseBean(message, code);
    }

    public ResponseBean() {
        this.code = "000000";
        this.message = this.getValue("systemCode", this.code);
    }

    public ResponseBean(T data) {
        this.data = data;
    }

    public ResponseBean(String message) {
        this.message = message;
    }

    public ResponseBean(String message, String code) {
        this.message = message;
        this.code = code;
    }

    @JsonIgnore
    public T getDataUse(int type) {
        if (this.err != null) {
            this.code = this.err.get("code").toString();
            this.message = this.err.get("message").toString();
        }

        if (!"000000".equals(this.code)) {
            if (!"500".equals(this.code) && null != this.code && !"".equals(this.code)) {
                if (type == 1) {
                    throw new JoyException(this.code, this.message);
                } else {
                    throw new BusinessException(this.code, this.message);
                }
            } else {
                throw new FeignCallException("600");
            }
        } else {
            return this.data;
        }
    }

    @JsonIgnore
    public T getDataUse(int type, boolean transactional) throws Exception {
        if (this.err != null) {
            this.code = this.err.get("code").toString();
            this.message = this.err.get("message").toString();
        }

        if (!"000000".equals(this.code)) {
            if (!"500".equals(this.code) && null != this.code && !"".equals(this.code)) {
                if (type == 1) {
                    if (transactional) {
                        throw new JoyException(this.code, this.message);
                    } else {
                        throw new JoyNoTransactionalException(this.code, this.message);
                    }
                } else if (transactional) {
                    throw new BusinessException(this.code, this.message);
                } else {
                    throw new BusinessNoTransactionalException(this.code, this.message);
                }
            } else {
                throw new FeignCallException("600");
            }
        } else {
            return this.data;
        }
    }

    public T getData() {
        return this.data;
    }

    public void setData(T data) {
        this.data = data;
    }

    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getMessage() {
        return this.message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public String getValue(String fileName, String key) {
        if (!StringUtils.isEmpty(fileName) && !StringUtils.isEmpty(key)) {
            Properties prop = new Properties();
            InputStream inStream = null;

            try {
                inStream = Thread.currentThread().getContextClassLoader().getResourceAsStream(fileName + ".properties");
                BufferedReader br = new BufferedReader(new InputStreamReader(inStream, "UTF-8"));
                prop.load(br);
                String var6 = prop.getProperty(key);
                return var6;
            } catch (IOException var16) {
                logger.error("getValue:fileName--" + fileName + "--key:" + key);
                var16.printStackTrace();
            } finally {
                if (null != inStream) {
                    try {
                        inStream.close();
                    } catch (IOException var15) {
                        var15.printStackTrace();
                    }
                }

            }

            return null;
        } else {
            return null;
        }
    }

    public void setErr(Map<String, Object> err) {
        this.err = err;
    }
}
`
