### ISSUE TITLE
首页推荐图标库怎么设置

### ISSUE THREAD

**Issue by highstars-gxx** [bolin-L/nicon#12]

**Comment by bolin-L** [comment]
需要自己postman调用接口

post  /api/repo/recommend/add

body参数：

{
	"key": "NXArUDVwNlg1cGl2NUxpcTVhU241YmlGNllDOA==", // /server/config/config.js salt字段的值
	"repos": [
		{
			"repoId": 71 // 需要添加的项目ID
		}
	]
}

**Comment by highstars-gxx** [comment]
I got it,thanks~
