### ISSUE TITLE
koa服务启动时候 总报mongodb的错

### ISSUE THREAD

**Issue by llsldwy** [bolin-L/nicon#14]
0|iconServ | [D] [2022-06-29 11:02:15.456] - connect redis success
0|iconServ | [D] [2022-06-29 11:02:15.490] - disconnect mongodb, dbUrl: mongodb://mongoadmin:mongo123456@172.24.28.14:27017/iconRepo, reason: undefined
PM2        | App [iconServer] with id [0] and pid [71649], exited with code [1] via signal [SIGINT]
PM2        | Starting execution sequence in -fork mode- for app name:iconServer id:0
PM2        | App name:iconServer id:0 online
0|iconServ | Wed, 29 Jun 2022 03:02:15 GMT koa deprecated Support for generators will be removed in v3. See the documentation for examples of how to convert old middleware https://github.com/koajs/koa/blob/master/docs/migration.md at index.js:93:9

帮忙看下，这个是什么原因，是因为mongodb 不对吗，还是koa版本不对

**Comment by bolin-L** [comment]
Koa版本应该不是问题，我看mongodb连接失败报错信息都没有，暂时排查不了，你可以尝试本地安装低版本的mongodb试试

```
nodejs v8.17.0(由于模块不兼容，node版本超过8之后就出现启动失败问题，需要整体升级)
npm 6.13.4
mogondb 3.2+
redis 3.2+

```

我后续抽时间把整个项目升级一下

**Comment by junjie-lean** [comment]
环境确实比较老了，需要作者升级一下。
