### ISSUE TITLE
你好，請問有下載打包的功能嗎？

### ISSUE THREAD

**Issue by yoruponder** [bolin-L/nicon#2]
像icomoon 這樣的下載打包，會生成一個css和font文件夾
看了這套系統生成的css，和icomoon生成的css一樣耶

**Comment by bolin-L** [comment]
暂时还没有这个功能。
不知道你使用的方式是怎么样的，这个平台推荐的是直接把css与font资源放到服务器或CDN上，其他的使用方式我不是很了解，如果有很多这样的需求的话，我可以考虑后续加上这个功能

**Comment by yoruponder** [comment]
谢谢~~
