### ISSUE TITLE
安装不了哦 

### ISSUE THREAD

**Issue by guojingyinan219** [bolin-L/nicon#6]
npm http fetch GET 403 http://rnpm.hz.netease.com/thunkify-wrap 19ms

**Comment by guojingyinan219** [comment]
![image](https://user-images.githubusercontent.com/13974995/64663830-a1ae4a80-d47f-11e9-8914-56b7a540427a.png)

**Comment by bolin-L** [comment]
我试过了没有问题  是不是你网易的源有问题  切个源重新安装试试

**Comment by guojingyinan219** [comment]
是源问题，已经好了
