### ISSUE TITLE
这个后面还考虑改进和优化吗 

### ISSUE THREAD

**Issue by guojingyinan219** [bolin-L/nicon#7]

**Comment by bolin-L** [comment]
优化的话看需求了，如果比较需要的点还是会加上，有问题的话还是会及时修复的

**Comment by jxs7754** [comment]
下载字体和css的功能

**Comment by bolin-L** [comment]
@jxs7754  你一定要手动下载的吗  我之前写过工具的，你看看能不能满足你的需求  https://github.com/berlin-L/neicon-tool
