### ISSUE TITLE
我从淘宝iconfont上下载的svg 生成字体库的时候 svgo处理过的svg bug

### ISSUE THREAD

**Issue by Niwei** [bolin-L/nicon#8]
环境windos10  我从淘宝iconfont上下载的svg 生成字体库的时候 svgo处理过的svg 进行 gulp-iconfont 处理的时候 有的图标 直接Streaming not supported 我发现淘宝上的svg path里的 比如 1 1 0 会被svgo处理成110 gulp-iconfont glyphs 就处理不了 不识别  有的svg是可以的 还在排查原因

**Comment by Niwei** [comment]
找到原因就是svgo优化的原因 会把类似1 1 0这种字段去除空格合并成110 然后gulp-iconfont 就不识别这种path了 
解决方案：

1. 升级gulp生成字体的相关依赖，此时会遇到Streaming not supported 的问题参考 [https://github.com/bolin-L/nicon/issues/5](url) 
2. 修改了svgo的优化 将配置 convertPathData:false 就可以了 建议方案1

**Comment by jxs7754** [comment]
@Niwei 你好，我这边只能生成ttf文件，而且ttf文件是空的。遇到过这种问题吗

**Comment by Niwei** [comment]
> @Niwei 你好，我这边只能生成ttf文件，而且ttf文件是空的。遇到过这种问题吗

我的没问题的，我没用作者代码，作者的不适合我，我重写了一套，生成字体部分参考了作者的tool文件的 icon.js  gulp-iconfont，目前生成的ttf没遇到空问题，如果只能生成ttf的话建议参考https://github.com/bolin-L/nicon/issues/5 一般都是这个问题

**Comment by jxs7754** [comment]
@Niwei 谢谢哈，我换个账号登陆好使了，不知道什么问题

**Comment by jxs7754** [comment]
![image](https://user-images.githubusercontent.com/33508826/68364551-3d4ef500-0169-11ea-82b0-84e899c7b3a6.png)
@Niwei @bolin-L 你好 ， '{eot}'  '{ttf}' 是怎么用的吗

**Comment by Niwei** [comment]
> ![image](https://user-images.githubusercontent.com/33508826/68364551-3d4ef500-0169-11ea-82b0-84e899c7b3a6.png)
> @Niwei @bolin-L 你好 ， '{eot}' '{ttf}' 是怎么用的吗

这是模板  gulp任务处理的时候会去替换这里面的变量，下面’{eot}‘这些变量 作者在字体上传成功后替换成cdnhost的路径

**Comment by jxs7754** [comment]
![image](https://user-images.githubusercontent.com/33508826/68391092-c4b85a80-01a1-11ea-8663-f2930d4ca059.png)
@bolin-L 我这边 ttf woff svg 都替换了但是eot为啥替换不了呢，有时候ttf woff也替换不了，这些文件都正常生成

**Comment by Niwei** [comment]
> ![image](https://user-images.githubusercontent.com/33508826/68391092-c4b85a80-01a1-11ea-8663-f2930d4ca059.png)
> @bolin-L 我这边 ttf woff svg 都替换了但是eot为啥替换不了呢，有时候ttf woff也替换不了，这些文件都正常生成

debug一下replaceFontsInCss这个方法 看看参数各种以及替换方法有没有问题应该就行了，或者你直接在gulp处理模板的时候就把路径替换了，不用等到上传的时候替换

**Comment by jxs7754** [comment]
@Niwei 非常感谢，一下子有点清醒了，我还一直以为是gulp的问题

**Comment by bolin-L** [comment]
@Niwei 验证通过 感谢

**Comment by yinshipeng** [comment]
> 找到原因就是svgo优化的原因 会把类似1 1 0这种字段去除空格合并成110 然后gulp-iconfont 就不识别这种path了 解决方案：
> 
> 1. 升级gulp生成字体的相关依赖，此时会遇到Streaming not supported 的问题参考 [https://github.com/bolin-L/nicon/issues/5](url)
> 2. 修改了svgo的优化 将配置 convertPathData:false 就可以了 建议方案1

-----------------------------------------------
两种方案我都试了，sync接口仍然会报502错误
